@host = 127.0.0.1
@port = 8000
@baseUrl = http://{{host}}:{{port}}/api/trainings
#Test Request to JSON Placeholder
GET https://jsonplaceholder.typicode.com/todos/1 HTTP/1.1
Content-Type: application/json
###

@trainingId = 62dd4f38-ab30-44a5-84df-04458c82596a
@authorization = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmNzhkYWRjNi01OTAzLTQwNzktOTNhMy0yNTdkMGE0NTk1MmUiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsIm5hbWUiOiJUb255Iiwicm9sZSI6ImNsaWVudCIsImlhdCI6MTcxOTA5MTA5MSwiZXhwIjoxNzE5MDkxOTkxfQ.UHWMTLSv5X9dbSlaIxgYQY_VUPoemQvvj15QKwpqDWk

# Create new training
POST {{baseUrl}}/ HTTP/1.1
Content-Type: application/json

{
  "title": "Run, Forest",
  "background": "some/training/background.jpg",
  "userLevel": "профессионал",
  "trainingType": "кроссфит",
  "trainingDuration": "30-50",
  "price": 2500,
  "calories": 1500,
  "description": "impossible crossfit training for real beasts",
  "gender": "мужской",
  "video": "add/video/later.avi",
  "trainersName": "Evil",
  "isSpecial": true
}
###

# Get trainings list
GET {{baseUrl}}/ HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Get trainings list (+ price filtering)
GET {{baseUrl}}/?priceFrom=2000&priceTo=3000&sortType=price HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Get trainings list (+ calories filtering)
GET {{baseUrl}}/?caloriesFrom=1000&caloriesTo=1100&sortType=calories HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Get trainings list (+ rating filtering)
GET {{baseUrl}}/?ratingFrom=0&ratingTo=3&sortType=rating HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Get detail info about training
GET {{baseUrl}}/{{trainingId}} HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Update training
PATCH {{baseUrl}}/{{trainingId}} HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "rating": 5
}
###

# Delete training
DELETE {{baseUrl}}/{{trainingId}} HTTP/1.1
Content-Type: application/json
{{authorization}}
###


