@host = 127.0.0.1
@port = 8000
@baseUrl = http://{{host}}:{{port}}/api/balance

@balanceId = 905fae0b-d0ed-4fad-bab3-a8ec6c8b9090
@trainingId = 62dd4f38-ab30-44a5-84df-04458c82596a
@orderId = 201c2a72-d2a9-4b03-8ee1-0f4a5fa1d272
@authorization = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ZDRkYzliMC00OTk4LTQ4YTAtYTYwMi03YWE0NThmNDMzODgiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsIm5hbWUiOiJUb255Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzIxNzQzNjEwLCJleHAiOjE3MjE3NDQ1MTB9.apeJ1lcj08eogUhSq5RIH24XQYozD44893N9QW74W8Q

# Create new balance
POST {{baseUrl}}/ HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "trainingId": "573eeb95-d518-476b-8f58-fcba4879a732",
  "remainingTrainingsCount": 1
}
###

# Get user balance
GET {{baseUrl}}/?limit=30 HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Count user`s availible trainings count (balance)
GET {{baseUrl}}/count HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Update balance
PATCH {{baseUrl}}/{{balanceId}} HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "remainingTrainingsCount": 10
}
###

# Delete balance
DELETE {{baseUrl}}/{{balanceId}} HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Decrease training balance
PATCH {{baseUrl}}/decrease HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "trainingId": "573eeb95-d518-476b-8f58-fcba4879a732",
  "amount": 1
}
###

# Increase training balance
PATCH {{baseUrl}}/increase HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "trainingId": "573eeb95-d518-476b-8f58-fcba4879a732",
  "amount": 1
}
###