@host = 127.0.0.1
@port = 8000
@baseUrl = http://{{host}}:{{port}}/api/balance

@balanceId = 021a2fc1-ce89-439f-b2e6-6f7976114c64
@serviceId = 021a2fc1-ce89-439f-b2e6-6f7976114c64
@authorization = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMzJjM2I5Mi0wNzA4LTQ3ZDYtYWJiZC01MzFkZGNjOTVkNjMiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsIm5hbWUiOiJUb255Iiwicm9sZSI6ImNsaWVudCIsImlhdCI6MTcxOTA4MzU1OSwiZXhwIjoxNzE5MDg0NDU5fQ.FEoHcJGtXwxDw6_boS5xOGl3Rp_CU_y-bOTyLKNFW-8

# Create new balance
POST {{baseUrl}}/ HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "balanceId": "3bac977b-12ce-44c3-8dc4-c3a9e4e71794",
  "remainingTrainingsCount": "3bac977b-12ce-44c3-8dc4-c3a9e4e71794",
}
###

# Get user balance
GET {{baseUrl}}/?limit=20 HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Get detail info about balance
GET {{baseUrl}}/{{balanceId}} HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Update balance
PATCH {{baseUrl}}/{{balanceId}} HTTP/1.1
Content-Type: application/json
{{authorization}}
{
  "remainingTrainingsCount": 2
}
###

# Delete balance
DELETE {{baseUrl}}/{{balanceId}} HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Training balance
GET {{baseUrl}}/balance HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Decrease training balance
PATCH {{baseUrl}}/decrease/{{serviceId}}/3 HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Increase training balance
PATCH {{baseUrl}}/balance/increase/{{serviceId}}/3 HTTP/1.1
Content-Type: application/json
{{authorization}}
###