@host = 127.0.0.1
@port = 8000
@baseUrl = http://{{host}}:{{port}}/api/balance

@balanceId = e3772d69-748f-4958-9a1e-0f5611928c61
@serviceId = 62dd4f38-ab30-44a5-84df-04458c82596a
@orderId = 201c2a72-d2a9-4b03-8ee1-0f4a5fa1d272
@authorization = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmNzhkYWRjNi01OTAzLTQwNzktOTNhMy0yNTdkMGE0NTk1MmUiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsIm5hbWUiOiJUb255Iiwicm9sZSI6ImNsaWVudCIsImlhdCI6MTcxOTA5MjAyOSwiZXhwIjoxNzE5MDkyOTI5fQ.1F1LQC0yWxhwick7B1y39dGG-WezpiP5_Ky37hIMY4Q

# Create new balance
POST {{baseUrl}}/ HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "orderId": "201c2a72-d2a9-4b03-8ee1-0f4a5fa1d272",
  "remainingTrainingsCount": 10
}
###

# Get user balance
GET {{baseUrl}}/?limit=20 HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Get detail info about balance
GET {{baseUrl}}/{{balanceId}} HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Update balance
PATCH {{baseUrl}}/{{balanceId}} HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "remainingTrainingsCount": 10
}
###

# Delete balance
DELETE {{baseUrl}}/{{balanceId}} HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Decrease training balance
PATCH {{baseUrl}}/decrease/{{serviceId}}/3 HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Increase training balance
PATCH {{baseUrl}}/increase/{{serviceId}}/3 HTTP/1.1
Content-Type: application/json
{{authorization}}
###