@host = 127.0.0.1
@port = 8000
@baseUrl = http://{{host}}:{{port}}/api/requests

@requestId = d11424fb-88c2-4ad9-8891-7a28c9aed279
@targetUserId = 5f5e211a-4295-4e5b-8893-787d7c435b9c
@authorization = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxNmM2NmFlZC0xMmEyLTQ3NjktYTY0NS02MDA0OTc0MGU3NjAiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsIm5hbWUiOiJUb255Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzI2MjM5NTExLCJleHAiOjE3MjYyNDA0MTF9.eSkVGBygiBkCPaZPCwkoGUP-30WiuThQ132F2HvBZUc


# Create new request
POST {{baseUrl}}/ HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "requestType": "friendship",
  "targetUserId": "5f5e211a-4295-4e5b-8893-787d7c435b9c"
}
###

# Update request
PATCH {{baseUrl}}/{{requestId}} HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "status": "Принят"
}
###

# Delete request
DELETE {{baseUrl}}/{{requestId}} HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Get all target`s requests
GET {{baseUrl}}/{{targetUserId}} HTTP/1.1
{{authorization}}
###