@host = 127.0.0.1
@port = 8000
@baseUrl = http://{{host}}:{{port}}/api/requests

@requestId = 354dd173-8091-4094-8c65-04feda38e423
@initiatorUserId = fe302885-fb20-4b7f-a381-862d9f1eb0c2
@targetUserId = fe302885-fb20-4b7f-a381-862d9f1eb0c2
@authorization = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZTMwMjg4NS1mYjIwLTRiN2YtYTM4MS04NjJkOWYxZWIwYzIiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsIm5hbWUiOiJUb255Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzI2NDI4MDg4LCJleHAiOjE3MjY0Mjg5ODh9.VtP39NP5TSfANLIuL_fausSi6KblhI0psZpX9ic4niQ


# Create new request
POST {{baseUrl}}/ HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "requestType": "friendship",
  "targetUserId": "88e22b85-1e96-4425-b9c7-a3f36e921617"
}
###

# Update request
PATCH {{baseUrl}}/{{requestId}} HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "status": "Принят"
}
###

# Delete request
DELETE {{baseUrl}}/{{requestId}} HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Get all requests to target user
GET {{baseUrl}}/by-target/{{targetUserId}} HTTP/1.1
{{authorization}}
###

# Get all requests by initiator user
GET {{baseUrl}}/by-initiator/{{initiatorUserId}} HTTP/1.1
{{authorization}}
###