@host = 127.0.0.1
@port = 8000
@baseUrl = http://{{host}}:{{port}}/api/orders

@orderId = 201c2a72-d2a9-4b03-8ee1-0f4a5fa1d272
@authorization = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmNzhkYWRjNi01OTAzLTQwNzktOTNhMy0yNTdkMGE0NTk1MmUiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsIm5hbWUiOiJUb255Iiwicm9sZSI6ImNsaWVudCIsImlhdCI6MTcxOTA5MTA5MSwiZXhwIjoxNzE5MDkxOTkxfQ.UHWMTLSv5X9dbSlaIxgYQY_VUPoemQvvj15QKwpqDWk

# Create new order
POST {{baseUrl}}/ HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "type": "абонемент",
  "serviceId": "b3110e27-cb56-4c74-b633-d71d697f03e9",
  "trainingsCount": 5,
  "paymentType": "mir"
}
###

# Get orders list
GET {{baseUrl}}/?limit=20 HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Get detail info about order
GET {{baseUrl}}/{{orderId}} HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Update order
PATCH {{baseUrl}}/{{orderId}} HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "trainingsCount": 10
}
###

# Delete order
DELETE {{baseUrl}}/{{orderId}} HTTP/1.1
Content-Type: application/json
{{authorization}}
###