@host = 127.0.0.1
@port = 8000
@baseUrl = http://{{host}}:{{port}}/api/orders

@orderId = a7f20914-e2c2-43fa-96eb-074ebf86b58e
@authorization = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNDk0MjdkOC05ODdlLTQ5MmEtOTg1Yi1kYmJiOWRmNmU4OWQiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsIm5hbWUiOiJUb255Iiwicm9sZSI6ImNsaWVudCIsImlhdCI6MTcxOTA3NTg1MiwiZXhwIjoxNzE5MDc2NzUyfQ.dXkqMR7SXTrH1V5_0A0X_LteRuH9rTdFJDWo5968qPE

# Create new order
POST {{baseUrl}}/ HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "type": "абонемент",
  "serviceId": "fcc98b5e-ed0b-48ee-ae08-7a9f06c6114f",
  "trainingsCount": 10,
  "paymentType": "mir"
}
###

# Get orders list
GET {{baseUrl}}/?limit=20 HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Get detail info about order
GET {{baseUrl}}/{{orderId}} HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Update order
PATCH {{baseUrl}}/{{orderId}} HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "price": 1000
}
###

# Delete order
DELETE {{baseUrl}}/{{orderId}} HTTP/1.1
Content-Type: application/json
{{authorization}}
###


