@host = 127.0.0.1
@port = 8000
@baseUrl = http://{{host}}:{{port}}/api/training-reviews
#Test Request to JSON Placeholder
GET https://jsonplaceholder.typicode.com/todos/1 HTTP/1.1
Content-Type: application/json
###

@authorization = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjYzAxMWY3NC00OTI2LTQ2NTMtYTEyNi1kNzYwMjI1NDZmMmIiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsIm5hbWUiOiJUb255Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzIzMDMzMzc3LCJleHAiOjE3MjMwMzQyNzd9.CRA-CxhqspORvVrxCXBVzp3gJlipGa0BUF5eDMbgb8M
@trainingId = f93637e0-e8b7-4579-b478-cbede67bdcce
@reviewId = 81179d69-e1cb-4b42-8631-db8e8c3b89ca

GET {{baseUrl}}/{{trainingId}} HTTP/1.1
Content-Type: application/json
{{authorization}}
###

POST {{baseUrl}}/{{trainingId}} HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "rating": 3,
  "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed finibus neque elit, quis rutrum turpis."
}
###

PATCH {{baseUrl}}/{{trainingId}}/{{reviewId}} HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "text": "123456 ipsum dolor sit amet, consectetur adipiscing elit. Sed finibus neque elit, quis rutrum turpis."
}
###

DELETE {{baseUrl}}/{{trainingId}}/{{reviewId}} HTTP/1.1
Content-Type: application/json
{{authorization}}
###
