@host = 127.0.0.1
@port = 8000
@baseUrl = http://{{host}}:{{port}}/api/users
#Test Request to JSON Placeholder
GET https://jsonplaceholder.typicode.com/todos/1 HTTP/1.1
Content-Type: application/json
###

@userId = d61ef04e-295a-41cb-a230-7e9e4570f14b
@authorization = Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNjFlZjA0ZS0yOTVhLTQxY2ItYTIzMC03ZTllNDU3MGYxNGIiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsIm5hbWUiOiJUb255Iiwicm9sZSI6IiIsImlhdCI6MTcxODU0NzQwMywiZXhwIjoxNzE4NTQ4MzAzfQ.JLPrtuK8YGibm1wf_WWISE77ZXUtU7bkwKsd2J0DVV4
@refresh = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNjFlZjA0ZS0yOTVhLTQxY2ItYTIzMC03ZTllNDU3MGYxNGIiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsIm5hbWUiOiJUb255Iiwicm9sZSI6IiIsInRva2VuSWQiOiI1MzQwYjI0Yi01ZDQxLTRmYTMtOTNjMC1jNWYwMmY5ZWJkODkiLCJpYXQiOjE3MTg1NDc0MDMsImV4cCI6MTcxODU0ODMwM30.CJJ2j0JsbpjcXdg-PYjZP2kCp37odwgkyQr3TUWbqkI

# /////////////////////////////////// AUTNENTICATION ///////////////////////////////////

# Create new user
POST {{baseUrl}}/register/ HTTP/1.1
Content-Type: application/json

{
  "email": "iron-man@starkindustries.it",
  "name": "Tony",
  "password": "jarvis-123",
  "gender": "мужской",
  "location": "звездная"
}

###

# Login user
POST  {{baseUrl}}/login/ HTTP/1.1
Content-Type: application/json

{
  "email": "iron-man@starkindustries.it",
  "password": "jarvis-123"
}
###

# Check JWT Token & get token payload
POST {{baseUrl}}/check/ HTTP/1.1
{{authorization}}
###

# Get new JWT pair: Token + Refresh token
POST {{baseUrl}}/refresh/ HTTP/1.1
{{refresh}}
###

# /////////////////////////////////// USER ///////////////////////////////////

# Get detail info about user
GET  {{baseUrl}}/{{userId}} HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "userId": "817ddac9-08dd-4084-882c-f1d1381f1243"
}
###

# Delete user
DELETE {{baseUrl}}/{{userId}} HTTP/1.1
{{authorization}}
###
