@host = 127.0.0.1
@port = 8000
@baseUrl = http://{{host}}:{{port}}/api/users
#Test Request to JSON Placeholder
GET https://jsonplaceholder.typicode.com/todos/1 HTTP/1.1
Content-Type: application/json
###

@userId = fe302885-fb20-4b7f-a381-862d9f1eb0c2
@authorization = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZTMwMjg4NS1mYjIwLTRiN2YtYTM4MS04NjJkOWYxZWIwYzIiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsIm5hbWUiOiJUb255Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzI2NDI3MTE0LCJleHAiOjE3MjY0MjgwMTR9.FEmIWDHdN9YsTGdubpEb2UHA5qbzp0M198Z1A778i_Q
@refresh = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZTMwMjg4NS1mYjIwLTRiN2YtYTM4MS04NjJkOWYxZWIwYzIiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsIm5hbWUiOiJUb255Iiwicm9sZSI6ImFkbWluIiwidG9rZW5JZCI6ImJkMGZlZGJkLWY1MzctNDlmNS04MWM1LWY3OGE1ODcyZDVmMSIsImlhdCI6MTcyNjM5ODY0MSwiZXhwIjoxNzI2Mzk5NTQxfQ.KenTHvB3m33IQRzm2IfYkwmmctRA4BonFA-dSiUyBtU

# /////////////////////////////////// AUTNENTICATION ///////////////////////////////////
# Create new user
POST {{baseUrl}}/register/ HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "email": "iron-man@stark.it",
  "name": "Tony",
  "password": "jarvis-123",
  "gender": "мужской",
  "location": "звездная",
  "dayCaloriesLimit": 2800
}
###

# Login user
POST  {{baseUrl}}/login/ HTTP/1.1
Content-Type: application/json

{
  "email": "iron-man@starkindustries.it",
  "password": "jarvis-123"
}

# {
#   "email": "test@yandex.ru",
#   "password": "123456"
# }
###

# Check JWT Token & get token payload
POST {{baseUrl}}/check/ HTTP/1.1
{{authorization}}
###

# Get new JWT pair: Token + Refresh token
POST {{baseUrl}}/refresh/ HTTP/1.1
{{refresh}}
###

# /////////////////////////////////// USER ///////////////////////////////////
# Get users list
GET {{baseUrl}}/search HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Get detail info about user
GET {{baseUrl}}/ HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Update user
PATCH {{baseUrl}}/ HTTP/1.1
Content-type: application/json
{{authorization}}

{
  "birthDate": "1993-09-26"
}
###

# Delete user
DELETE {{baseUrl}}/{{userId}} HTTP/1.1
{{authorization}}
###

# Get additional info
GET {{baseUrl}}/additional HTTP/1.1
###

# /////////////////////////////////// FRIENDSHIP ///////////////////////////////////

# Add friend to current user
POST {{baseUrl}}/friends HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "targetUserId": "6cc72360-96e7-4c88-ad60-649b31d2af4a"
}
###

# Remove friend from current user
DELETE {{baseUrl}}/friends HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "targetUserId": "6cc72360-96e7-4c88-ad60-649b31d2af4a"
}
###

# Remove friend from other user
DELETE {{baseUrl}}/friends HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "otherCurrentUser": "8c132bfa-b758-40ab-9663-b1f637848d04",
  "targetUserId": "6cc72360-96e7-4c88-ad60-649b31d2af4a"
}
###

# /////////////////////////////////// SEARCH ///////////////////////////////////
# Default
GET {{baseUrl}}/search/ HTTP/1.1
{{authorization}}
###

# By role
GET {{baseUrl}}/search/?role=client HTTP/1.1
{{authorization}}
###

# By level
GET {{baseUrl}}/search/?level=профессионал HTTP/1.1
{{authorization}}
###

# By TrainingType
GET {{baseUrl}}/search/?trainingType=йога&trainingType=стретчинг HTTP/1.1
{{authorization}}
###

# isReadyToTraining
GET {{baseUrl}}/search/?isReadyToTraining=false HTTP/1.1
{{authorization}}
###

# Complex: By level & Role
GET {{baseUrl}}/search/?level=профессионал&role=trainer HTTP/1.1
{{authorization}}
###