@host = 127.0.0.1
@port = 8000
@baseUrl = http://{{host}}:{{port}}/api/users
#Test Request to JSON Placeholder
GET https://jsonplaceholder.typicode.com/todos/1 HTTP/1.1
Content-Type: application/json
###

@userId = 61f2e83e-5b2b-407e-9004-516914ad3ad7
@authorization = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZTMwMjg4NS1mYjIwLTRiN2YtYTM4MS04NjJkOWYxZWIwYzIiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsIm5hbWUiOiJUb255Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzI2MzE2NTAxLCJleHAiOjE3MjYzMTc0MDF9.Quw1yxNwDb8XFULW5QN5zvEK7OjmKYo76JKVRca7pGo
@refresh = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZTMwMjg4NS1mYjIwLTRiN2YtYTM4MS04NjJkOWYxZWIwYzIiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsIm5hbWUiOiJUb255Iiwicm9sZSI6ImFkbWluIiwidG9rZW5JZCI6ImU0ZGVhZmFjLTUxYjYtNDQ2MS1iMmI1LWU0Y2U4NTc1ZDdmNCIsImlhdCI6MTcyNjMxNTU4OCwiZXhwIjoxNzI2MzE2NDg4fQ.eSZDvooBn7Z6G95kXWbJEcRJkN6fEO4kNjm7InHqPyo

# /////////////////////////////////// AUTNENTICATION ///////////////////////////////////
# Create new user
POST {{baseUrl}}/register/ HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "email": "iron-man@stark.it",
  "name": "Tony",
  "password": "jarvis-123",
  "gender": "мужской",
  "location": "звездная",
  "dayCaloriesLimit": 2800
}
###

# Login user
POST  {{baseUrl}}/login/ HTTP/1.1
Content-Type: application/json

{
  "email": "iron-man@starkindustries.it",
  "password": "jarvis-123"
}

# {
#   "email": "test@yandex.ru",
#   "password": "123456"
# }
###

# Check JWT Token & get token payload
POST {{baseUrl}}/check/ HTTP/1.1
{{authorization}}
###

# Get new JWT pair: Token + Refresh token
POST {{baseUrl}}/refresh/ HTTP/1.1
{{refresh}}
###

# /////////////////////////////////// USER ///////////////////////////////////
# Get detail info about user
GET {{baseUrl}}/ HTTP/1.1
Content-Type: application/json
{{authorization}}
###

# Update user
PATCH {{baseUrl}}/ HTTP/1.1
Content-type: application/json
{{authorization}}

{
  "birthDate": "1993-09-26"
}
###

# Delete user
DELETE {{baseUrl}}/{{userId}} HTTP/1.1
{{authorization}}
###

# Get additional info
GET {{baseUrl}}/additional HTTP/1.1
###

# /////////////////////////////////// FRIENDSHIP ///////////////////////////////////

# Add friend to current user
POST {{baseUrl}}/friends HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "targetUserId": "83937b80-0168-41d6-9677-adb39391f71b"
}
###

# Remove friend from current user
DELETE {{baseUrl}}/friends HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "targetUserId": "83937b80-0168-41d6-9677-adb39391f71b"
}